vaccines:
  - owid_name: "Abdala"
    org_name: "Abdala"
  - owid_name: "ZF2001"
    org_name: 
      - "Anhui ZL - Recombinant"
      - "RBD-Dimer"
      - "ZF2001"
  - owid_name: "Oxford/AstraZeneca"
    org_name: 
      - "AstraZeneca - AZD1222"
      - "AstraZeneca - Vaxzevria"
      - "SII - Covishield"
  - owid_name: "Sinopharm/Beijing"
    org_name: 
      - "Beijing CNBG - BBIBP-CorV"
      - "Beijing CNBG - Inactivated"
  - owid_name: "Covaxin"
    org_name: "Bharat - Covaxin"
  - org_name: "CanSino - Ad5-nCOV"
    owid_name: "CanSino"
  - org_name: "Gamaleya - Sputnik V"
    owid_name: "Sputnik V"
  - org_name: "Janssen - Ad26.COV 2.5"
    owid_name: "Johnson&Johnson"
  - org_name: "Moderna - mRNA-1273"
    owid_name: "Moderna"
  - org_name: "Novavax - Covavax"
    owid_name: "Novavax"
  - org_name: "Pfizer BioNTech - Comirnaty"
    owid_name: "Pfizer/BioNTech"
  - owid_name: "QazVac"
    org_name: 
      - "QazVac"
      - "RIBSP - QazCovid"
  - owid_name: "Sinopharm/HayatVax"
    org_name: "Sinopharm/HayatVax"
  - owid_name: "Sinovac"
    org_name: "Sinovac - CoronaVac"
  - owid_name: "Soberana02"
    org_name: "Soberana02"
  - owid_name: "EpiVacCorona"
    org_name: "SRCVB - EpiVacCorona"
  - owid_name: "Sinopharm/Wuhan"
    org_name: "Wuhan CNBG - Inactivated"

countries:
  - org_name: "Afghanistan"
    owid_name: "Afghanistan"
  - org_name: "Algeria"
    owid_name: "Algeria"
  - org_name: "Angola"
    owid_name: "Angola"
  - org_name: "Anguilla"
    owid_name: "Anguilla"
  - org_name: "Belarus"
    owid_name: "Belarus"
  - org_name: "Benin"
    owid_name: "Benin"
  - org_name: "Bhutan"
    owid_name: "Bhutan"
  - org_name: "Bonaire Sint Eustatius and Saba"
    owid_name: "Bonaire Sint Eustatius and Saba"
  - org_name: "British Virgin Islands"
    owid_name: "British Virgin Islands"
  - org_name: "Burkina Faso"
    owid_name: "Burkina Faso"
  - org_name: "Cabo Verde"
    owid_name: "Cape Verde"
  - org_name: "Cameroon"
    owid_name: "Cameroon"
  - org_name: "Central African Republic"
    owid_name: "Central African Republic"
  - org_name: "Chad"
    owid_name: "Chad"
  - org_name: "Comoros"
    owid_name: "Comoros"
  - org_name: "Democratic Republic of the Congo"
    owid_name: "Democratic Republic of Congo"
  - org_name: "Djibouti"
    owid_name: "Djibouti"
  - org_name: "Egypt"
    owid_name: "Egypt"
  - org_name: "Gabon"
    owid_name: "Gabon"
  - org_name: "Gambia"
    owid_name: "Gambia"
  - org_name: "Ghana"
    owid_name: "Ghana"
  - org_name: "Grenada"
    owid_name: "Grenada"
  - org_name: "Guinea-Bissau"
    owid_name: "Guinea-Bissau"
  - org_name: "Honduras"
    owid_name: "Honduras"
  - org_name: "Iran (Islamic Republic of)"
    owid_name: "Iran"
  - org_name: "Iraq"
    owid_name: "Iraq"
  - org_name: "Lao People's Democratic Republic"
    owid_name: "Laos"
  - org_name: "Lesotho"
    owid_name: "Lesotho"
  - org_name: "Liberia"
    owid_name: "Liberia"
  - org_name: "Libya"
    owid_name: "Libya"
  - org_name: "Kiribati"
    owid_name: "Kiribati"
  - org_name: "Madagascar"
    owid_name: "Madagascar"
  - org_name: "Mali"
    owid_name: "Mali"
  - org_name: "Mauritania"
    owid_name: "Mauritania"
  - org_name: "Mauritius"
    owid_name: "Mauritius"
  - org_name: "Montserrat"
    owid_name: "Montserrat"
  - org_name: "Mozambique"
    owid_name: "Mozambique"
  - org_name: "Myanmar"
    owid_name: "Myanmar"
  - org_name: "Nauru"
    owid_name: "Nauru"
  - org_name: "Nicaragua"
    owid_name: "Nicaragua"
  - org_name: "Niger"
    owid_name: "Niger"
  - org_name: "Nigeria"
    owid_name: "Nigeria"
  - org_name: "Oman"
    owid_name: "Oman"
  - org_name: "Papua New Guinea"
    owid_name: "Papua New Guinea"
  - org_name: "Rwanda"
    owid_name: "Rwanda"
  - org_name: "Sao Tome and Principe"
    owid_name: "Sao Tome and Principe"
  - org_name: "Senegal"
    owid_name: "Senegal"
  - org_name: "Sierra Leone"
    owid_name: "Sierra Leone"
  - org_name: "Sint Maarten"
    owid_name: "Sint Maarten (Dutch part)"
  - org_name: "Solomon Islands"
    owid_name: "Solomon Islands"
  - org_name: "Somalia"
    owid_name: "Somalia"
  - org_name: "South Sudan"
    owid_name: "South Sudan"
  - org_name: "Sudan"
    owid_name: "Sudan"
  - org_name: "Syrian Arab Republic"
    owid_name: "Syria"
  - org_name: "Tajikistan"
    owid_name: "Tajikistan"
  - org_name: "Timor-Leste"
    owid_name: "Timor"
  - org_name: "Togo"
    owid_name: "Togo"
  - org_name: "Turkmenistan"
    owid_name: "Turkmenistan"
  - org_name: "Turks and Caicos Islands"
    owid_name: "Turks and Caicos Islands"
  - org_name: "Tuvalu"
    owid_name: "Tuvalu"
  - org_name: "Uganda"
    owid_name: "Uganda"
  - org_name: "United Republic of Tanzania"
    owid_name: "Tanzania"
  - org_name: "Vanuatu"
    owid_name: "Vanuatu"
  - org_name: "Yemen"
    owid_name: "Yemen"